### ISSUE TITLE
http checker never reads responses, resulting in leaks and failed checks

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-checker#38]
I'll be posting more details shortly, but the http checker doesn't ever read any data from the responses it gets from the server it's checking.  As a result, the socket associated with the request is not re-used by Node.  I think the only reason this isn't a bigger problem is because in practice, we're contacting HTTP servers that themselves close idle sockets after sending short responses.  (Node servers do this by default after 2 minutes.)  When that happens, Node's built-in HTTP Agent removes the socket from the pool, creates a new socket, and uses that for the next request, so things seem to work (though we might leak the request and response objects).

This is much worse if the server doesn't close the socket or if the response has more data than Node will buffer.  We'll end up leaving the socket in use forever.  If this happens 5 times (the value of maxSockets in Node 0.10), then all subsequent requests to that host will queue up inside the HTTP agent.  The checks themselves fail after hitting a separate 5-minute check timeout, and the requests themselves still exist, resulting in an fd leak, a memory leak, and eventually a crash.

**Comment by davepacheco** [comment]
The details of the underlying issue are at https://smartos.org/bugview/MANTA-3091.

**Comment by davepacheco** [comment]
This may have been the underlying problem that we sought to work around under #27.

**Comment by timkordas** [comment]
The commit here: https://github.com/joyent/node-checker/commit/5a0d675b1ff228ec5c2bcef2b003aff8772381a7 consumes any outstanding data, and adds some tests for this (and other) behaviors for http-checks.
